#!/usr/bin/env bash
# set up 404
sudo apt-get update -y;
sudo apt-get install -y nginx;
sudo apt-get install -y ufw;

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo ufw allow 'OpenSSH';

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html;

sudo cp ./nginxconf /etc/nginx/sites-enabled/default;

sudo service nginx restart;